@extends('site.layouts._partials.header')
@section('hero')
    @component('site.layouts._components.hero')
    @endcomponent
    @component('site.layouts._components.sobremim')
    @endcomponent
    @component('site.layouts._components.projetos')
    @endcomponent
    @component('site.layouts._components.habilidades')
    @endcomponent
    @component('site.layouts._components.contato')
    @endcomponent
    @component('site.layouts._components.footer')
    @endcomponent
@endsection